### PR TITLE
Fix docker-compose test

### LINKED ISSUE #956: Docker Compose is broken on master
## Expected Behavior 

Bringing up Feast with docker compose works

## Current Behavior
Problem reported on mailing list
```
 docker-compose % docker-compose up -d

Pulling jobcontroller (gcr.io/kf-feast/feast-jobcontroller:0.6.2)...

ERROR: manifest for gcr.io/kf-feast/feast-jobcontroller:0.6.2 not found: manifest unknown: Failed to fetch "0.6.2" from request "/v2/kf-feast/feast-jobcontroller/manifests/0.6.2".
```

## Possible Solution

* Cut a new release of Feast
* Revert Docker Compose files

### PR DESCRIPTION
**Pull request by terryyylim**
**What this PR does / why we need it**:
`tests-docker-compose` test that triggers when PRs are merged to master branch currently runs tests on a specific version (eg. 0.6.2) image. This causes test failures since Dockerfiles may have changed since a specific version tag.

**Which issue(s) this PR fixes**:

Fixes #956 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: infra/scripts/test-docker-compose.sh [hunk 1]
```diff
@@ -26,6 +26,11 @@ export COMPOSE_INTERACTIVE_NO_CLI=1
 cd ${PROJECT_ROOT_DIR}/infra/docker-compose/
 cp .env.sample .env
 
+# Replace FEAST_VERSION with latest github image SHA
```
Comment (woop) [inline infra/scripts/test-docker-compose.sh:29]: Can we maybe just use an environmental variable here?

File: .github/workflows/master_only.yml [hunk 2]
```diff
@@ -64,4 +64,4 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Test docker compose
-        run: ./infra/scripts/test-docker-compose.sh
+        run: ./infra/scripts/test-docker-compose.sh ${GITHUB_SHA}
```
Comment (woop) [inline .github/workflows/master_only.yml:67]: I think it might also be better to move this test to the main workflow, along with the load test.

**Comment by woop** [comment]
Did you also have a look at the load test that is failing? https://github.com/feast-dev/feast/runs/1055084887?check_suite_focus=true

**Review by woop — APPROVED** [review]
